"""initial_schema

Revision ID: 20f2e01112f8
Revises: 
Create Date: 2026-05-27 20:26:19.931900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20f2e01112f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SEQUENCE IF NOT EXISTS facility_id_seq START 1")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('facility_id', sa.String(length=20), nullable=False),
    sa.Column('facility_name', sa.String(length=255), nullable=False),
    sa.Column('facility_type', sa.String(length=30), nullable=False),
    sa.Column('ownership', sa.String(length=30), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('physical_address', sa.String(), nullable=False),
    sa.Column('facility_phone', sa.String(length=30), nullable=False),
    sa.Column('facility_email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('plan_type', sa.String(length=20), nullable=True),
    sa.Column('subscription_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facilities')),
    sa.UniqueConstraint('facility_email', name=op.f('uq_facilities_facility_email')),
    sa.UniqueConstraint('facility_id', name=op.f('uq_facilities_facility_id'))
    )
    op.create_table('otp_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_otp_tokens_facility_id_facilities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_tokens'))
    )
    op.create_table('payment_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('plan_type', sa.String(length=20), nullable=False),
    sa.Column('momo_number', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('camp_start_date', sa.Date(), nullable=True),
    sa.Column('plan_start_date', sa.Date(), nullable=False),
    sa.Column('plan_end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_ref', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_payment_records_facility_id_facilities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_records')),
    sa.UniqueConstraint('reference', name=op.f('uq_payment_records_reference'))
    )
    op.create_table('specialists',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('specialist_name', sa.String(length=255), nullable=False),
    sa.Column('specialist_title', sa.String(length=50), nullable=False),
    sa.Column('licence_number', sa.String(length=100), nullable=False),
    sa.Column('specialist_phone', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_specialists_facility_id_facilities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_specialists'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specialists')
    op.drop_table('payment_records')
    op.drop_table('otp_tokens')
    op.drop_table('facilities')
    # ### end Alembic commands ###
    op.execute("DROP SEQUENCE IF EXISTS facility_id_seq")
