"""add_clinical_intake_and_hba1c_fields

Revision ID: def8b82d6b5a
Revises: 4f0109586844
Create Date: 2026-07-14 06:28:17.096175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'def8b82d6b5a'
down_revision: Union[str, Sequence[str], None] = '4f0109586844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prediction_records', sa.Column('waist_circumference', sa.Float(), nullable=True))
    op.add_column('prediction_records', sa.Column('cardiovascular_disease', sa.String(length=3), nullable=True))
    op.add_column('prediction_records', sa.Column('pcos', sa.String(length=3), nullable=True))
    op.add_column('prediction_records', sa.Column('gestational_diabetes', sa.String(length=3), nullable=True))
    op.add_column('prediction_records', sa.Column('smoking', sa.String(length=3), nullable=True))
    op.add_column('prediction_records', sa.Column('hba1c_result', sa.Float(), nullable=True))
    op.add_column('prediction_records', sa.Column('hba1c_comment', sa.String(length=50), nullable=True))
    op.add_column('prediction_records', sa.Column('hba1c_result_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prediction_records', 'hba1c_result_date')
    op.drop_column('prediction_records', 'hba1c_comment')
    op.drop_column('prediction_records', 'hba1c_result')
    op.drop_column('prediction_records', 'smoking')
    op.drop_column('prediction_records', 'gestational_diabetes')
    op.drop_column('prediction_records', 'pcos')
    op.drop_column('prediction_records', 'cardiovascular_disease')
    op.drop_column('prediction_records', 'waist_circumference')
    # ### end Alembic commands ###
